/*
 * Single-include public header for tivars_lib_cpp.
 * Generated by scripts/amalgamate.py. Do not edit manually.
 * Source commit: d50858661590be73afeceb64406391ea93643c30
 */

#ifndef TIVARS_LIB_CPP_AMALGAMATED_HPP
#define TIVARS_LIB_CPP_AMALGAMATED_HPP


// ===== src/CommonTypes.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef COMMON_H
#define COMMON_H

#include <vector>
#include <string>
#include <map>

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <tuple>

using data_t = std::vector<uint8_t>;
using options_t = std::map<std::string, int>;

#define u8enum(NAME) enum NAME : uint8_t

#endif


// ===== src/TypeHandlers/TypeHandlers.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TYPE_HANDLERS_H
#define TYPE_HANDLERS_H

// amalgamated: removed local include '../CommonTypes.h'

#if !defined(TH_GDB_SUPPORT)
#  if __cplusplus >= 201703L
#    if defined(__has_include)
#      if __has_include(<variant>)
#        define TH_GDB_SUPPORT 1
#      else
#        define TH_GDB_SUPPORT 0
#      endif
#    else
#      define TH_GDB_SUPPORT 1
#    endif
#  else
#    define TH_GDB_SUPPORT 0
#  endif
#endif

namespace tivars
{
    class TIVarFile;

    // See https://wikiti.brandonw.net/index.php?title=83Plus:OS:Variable_Versions
    enum TIVarFileMinVersionByte : uint8_t
    {
        VER_NONE         = 0x00,
        VER_83P_ALL      = 0x01,
        VER_83P_115      = 0x02,
        VER_83P_116      = 0x03,
        VER_84P_ALL      = 0x04,
        VER_84P_230      = 0x05,
        VER_84P_253MP    = 0x06,
        VER_84P_255MP    = 0x07,
        VER_84CSE_ALL    = 0x0A,
        VER_CE_ALL       = 0x0B,
        VER_CE_530       = 0x0C,
        VER_CE_EXACTONLY = 0x10,
        VER_CE_PYTHONMOD = 0x11,
        VER_INVALID      = 0xFF,
        MASK_USES_RTC    = 0b100000, // bit 5
    };
}

namespace tivars::TypeHandlers
{
#define th()    static data_t      makeDataFromString(const std::string& str, const options_t& options = options_t(), const TIVarFile* _ctx = nullptr); \
                static std::string makeStringFromData(const data_t& data,     const options_t& options = options_t(), const TIVarFile* _ctx = nullptr); \
                static TIVarFileMinVersionByte getMinVersionFromData(const data_t& data);

    class DummyHandler
    {
        public:
        DummyHandler() = delete;
        DummyHandler(const DummyHandler&) = delete;
        DummyHandler& operator=(const DummyHandler) = delete;
        th();
    };

    using TypeHandlersTuple = std::tuple<decltype(&DummyHandler::makeDataFromString), decltype(&DummyHandler::makeStringFromData), decltype(&DummyHandler::getMinVersionFromData)>;
    #define SpecificHandlerTuple(which) TypeHandlersTuple{ &(which::makeDataFromString), &(which::makeStringFromData), &(which::getMinVersionFromData) }

    class TH_GenericReal : public DummyHandler
    {
        public:
        th();
        static const constexpr size_t dataByteCount = 9;
    };

    class STH_FP : public TH_GenericReal
    {
    public:
        th();
        static const constexpr size_t dataByteCount = 9;
    };

    class STH_ExactFraction : public TH_GenericReal
    {
    public:
        th();
        static const constexpr size_t dataByteCount = 9;
    };

    class STH_ExactRadical : public TH_GenericReal
    {
    public:
        th();
        static const constexpr size_t dataByteCount = 9;
    };

    class STH_ExactPi : public TH_GenericReal
    {
    public:
        th();
        static const constexpr size_t dataByteCount = 9;
    };

    class STH_ExactFractionPi : public TH_GenericReal
    {
    public:
        th();
        static const constexpr size_t dataByteCount = 9;
    };

    class TH_GenericComplex : public DummyHandler
    {
        public:
        th();
        static const constexpr size_t dataByteCount = 2 * TH_GenericReal::dataByteCount;
    };

    class TH_GenericList : public DummyHandler
    {
        public:
        th();
        static const constexpr uint8_t listNameMarker = 0x5D;
    };

    class TH_Matrix : public DummyHandler
    {
        public:
        th();
    };

    class TH_GenericAppVar : public DummyHandler
    {
        public:
        th();
    };

    enum StructuredAppVarSubtype : uint8_t
    {
        APPVAR_SUBTYPE_PYTHON_MODULE = 0,
        APPVAR_SUBTYPE_PYTHON_IMAGE,
        APPVAR_SUBTYPE_STUDY_CARDS,
        APPVAR_SUBTYPE_STUDY_CARDS_SETTINGS,
        APPVAR_SUBTYPE_CELSHEET,
        APPVAR_SUBTYPE_CELSHEET_STATE,
        APPVAR_SUBTYPE_CABRIJR,
        APPVAR_SUBTYPE_NOTEFOLIO,
        APPVAR_SUBTYPE_NONE = 0xFF,
    };

    StructuredAppVarSubtype detectStructuredAppVarSubtype(const data_t& data);
    std::string detectStructuredAppVarTypeName(const data_t& data);

    class TH_StructuredAppVar : public TH_GenericAppVar
    {
    public:
        th();
    };

    class TH_Backup : public DummyHandler
    {
    public:
        struct backup_contents_t
        {
            bool hasData4 = false;
            uint16_t addressOfData2 = 0;
            data_t data1;
            data_t data2;
            data_t data3;
            data_t data4;
        };

        th();
        static backup_contents_t parseInternal(const data_t& data);
        static data_t buildInternal(const backup_contents_t& contents);
        static const constexpr uint16_t onFileMetaLength3 = 0x09;
        static const constexpr uint16_t onFileMetaLength4 = 0x0B;
        static const constexpr uint8_t internalSegmentCount3 = 3;
        static const constexpr uint8_t internalSegmentCount4 = 4;
        static const constexpr size_t internalHeaderByteCount3 = 9;
        static const constexpr size_t internalHeaderByteCount4 = 11;
    };

    class TH_Group : public DummyHandler
    {
    public:
        th();
        static const constexpr uint8_t archivedFlagValue = 0x80;
        static const constexpr size_t minimumDataByteCount = 2;
        static const constexpr size_t fixedNameByteCount = 3;
    };

    class TH_Picture : public DummyHandler
    {
    public:
        th();
        static const constexpr size_t minimumDataByteCount = 2;
        static const constexpr size_t monoPictureDataByteCount = 758;
        static const constexpr size_t colorPictureDataByteCount = 21947;
        static const constexpr size_t imageDataByteCount = 22247;
        static const constexpr size_t monoPictureWidth = 96;
        static const constexpr size_t monoPictureHeight = 63;
        static const constexpr size_t colorPictureWidth = 266;
        static const constexpr size_t colorPictureHeight = 165;
        static const constexpr size_t imageWidth = 133;
        static const constexpr size_t imageHeight = 83;
        static const constexpr uint8_t imageMagic = 0x81;
    };

    class STH_DataAppVar : public TH_GenericAppVar
    {
        public:
        th();
    };

    class STH_PythonAppVar : public TH_GenericAppVar
    {
        public:
        th();
        static const constexpr char ID_SCRIPT[] = "PYSC";
        static const constexpr char ID_CODE[] = "PYCD";
    };

    class TH_GDB : public DummyHandler
    {
        public:
        th();
        static const constexpr size_t dataByteCountMinimum = 100;
        static const constexpr char* magic84CAndLaterSectionMarker = "84C";
    };

    class TH_Settings : public DummyHandler
    {
        public:
        th();
        static const constexpr uint8_t typeReal = 0x00;
        static const constexpr uint8_t typeUndefinedReal = 0x0E;
        static const constexpr uint8_t typeWindowSettings = 0x0F;
        static const constexpr uint8_t typeRecallWindow = 0x10;
        static const constexpr uint8_t typeTableRange = 0x11;
        static const constexpr size_t realDataByteCount = TH_GenericReal::dataByteCount;
        static const constexpr size_t windowSettingsDataByteCount = 210;
        static const constexpr size_t recallWindowDataByteCount = 209;
        static const constexpr size_t tableRangeDataByteCount = 20;
        static const constexpr size_t windowSettingsHeaderByteCount = 3;
        static const constexpr size_t recallWindowHeaderByteCount = 2;
        static const constexpr size_t tableRangeHeaderByteCount = 2;
        static const constexpr uint8_t windowSettingsHeader[] = {0xD0, 0x00, 0x00};
        static const constexpr uint8_t recallWindowHeader[] = {0xCF, 0x00};
        static const constexpr uint8_t tableRangeHeader[] = {0x12, 0x00};
    };

    // Program, Protected Program, Y-Variable, String
    class TH_Tokenized : public DummyHandler
    {
        public:
        th();
        enum lang { LANG_EN = 0, LANG_FR, LANG_MAX };
        enum typelang { PRGMLANG_BASIC = 0, PRGMLANG_AXE, PRGMLANG_ICE };
        enum indentchar : char { INDENT_CHAR_SPACE = ' ', INDENT_CHAR_TAB = '\t' };
        struct token_posinfo { uint16_t line; uint16_t column; uint8_t len; };
        static std::string reindentCodeString(const std::string& str_orig, const options_t& options = options_t());
        static token_posinfo getPosInfoAtOffset(const data_t& data, uint16_t byteOffset, const options_t& options = options_t());
        static token_posinfo getPosInfoAtOffsetFromHexStr(const std::string& hexBytesStr, uint16_t byteOffset);
        static token_posinfo getPosInfoAtOffsetInSourceString(const std::string& sourceStr, uint16_t byteOffset);
        static std::string tokenToString(const data_t& data, int *incr, const options_t& options);
        static std::string oneTokenBytesToString(uint16_t tokenBytes);
    };

    // Special temporary type that may appear as an equation, during basic program execution
    class TH_TempEqu : public DummyHandler
    {
        public:
        th();
    };

#undef th

}

#endif


// ===== src/TIVarType.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIVARTYPE_H
#define TIVARTYPE_H

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'TypeHandlers/TypeHandlers.h'

namespace tivars
{

    class TIVarType
    {

    public:
        TIVarType() = default;

        explicit TIVarType(uint8_t id);
        TIVarType(const std::string& name);
        TIVarType(const char* name) { *this = TIVarType{std::string{name}}; }

        static TIVarType createFromID(uint8_t id) { return TIVarType{id}; }
        static TIVarType createFromName(const std::string& name) { return TIVarType{name}; }

        TIVarType(int id, const std::string& name, const std::vector<std::string>& exts, const TypeHandlers::TypeHandlersTuple& handlers)
        : id(id), name(name), exts(exts), handlers(handlers)
        {}

        ~TIVarType() = default;

        /* Getters */
        int getId() const { return this->id; }
        std::string getName() const { return this->name; }
        const std::vector<std::string>& getExts() const { return this->exts; }
        TypeHandlers::TypeHandlersTuple getHandlers() const { return this->handlers; };

    private:
        int id = -1;
        std::string name = "Unknown";
        std::vector<std::string> exts;
        TypeHandlers::TypeHandlersTuple handlers;

    };

}

#endif


// ===== src/TIModel.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIMODEL_H
#define TIMODEL_H

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'TIVarType.h'

namespace tivars
{

    class TIModel
    {

    public:
        TIModel() = default;
        TIModel(const std::string& name);
        TIModel(const char* name) { *this = TIModel{std::string{name}}; };

        TIModel(int orderId, const std::string& name, uint32_t flags, const std::string& sig, uint8_t productId, TIVarFileMinVersionByte minVersion)
        : orderID(orderId), name(name), flags(flags), sig(sig), productId(productId), minVersion(minVersion)
        {}

        ~TIModel() = default;

        /* Getters */
        int getOrderId() const { return this->orderID; }
        int getProductId() const { return this->productId; }
        std::string getName() const { return this->name; }
        uint32_t getFlags() const { return this->flags; }
        std::string getSig() const { return this->sig; }
        TIVarFileMinVersionByte getMinVersion() const { return this->minVersion; }

        bool supportsType(const TIVarType& type) const;

    private:
        int orderID      = -1;
        std::string name = "Unknown";
        uint32_t flags   = 0;
        std::string sig  = "";
        uint8_t productId = 0;
        TIVarFileMinVersionByte minVersion = VER_NONE;

    };

}

#endif


// ===== src/BinaryFile.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIVARS_LIB_CPP_BINARYFILE_H
#define TIVARS_LIB_CPP_BINARYFILE_H

// amalgamated: removed local include 'CommonTypes.h'

namespace tivars
{
    class BinaryFile
    {
    public:
        BinaryFile() = default;

        explicit BinaryFile(const std::string& filePath);

        BinaryFile(const BinaryFile&) = delete;
        BinaryFile& operator=(const BinaryFile) = delete;

        BinaryFile(BinaryFile&& o) noexcept : file(o.file), fileSize(o.fileSize)
        { o.file = nullptr; }

        ~BinaryFile()
        {
            close();
        }

        uint8_t get_raw_byte() const;
        data_t get_raw_bytes(size_t bytes) const;
        std::string get_string_bytes(size_t bytes) const;
        size_t size() const;
        void close();

    protected:
        FILE* file = nullptr;
        std::string filePath = "";
        size_t fileSize = 0;

    };
}

#endif //TIVARS_LIB_CPP_BINARYFILE_H


// ===== src/TIVarFile.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIVARS_LIB_CPP_TIVARFILE_H
#define TIVARS_LIB_CPP_TIVARFILE_H

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'BinaryFile.h'
// amalgamated: removed local include 'TIVarType.h'
// amalgamated: removed local include 'TIModel.h'

namespace tivars
{

    class TIVarFile : public BinaryFile
    {
    public:
        // For the record, 83+ = 4, 84+ = 10, 82A = 11, 84+CSE = 15, CE = 19, 84+T = 27...
        static const constexpr uint8_t OWNER_PID_NONE = 0;

        struct var_header_t
        {
            uint8_t  signature[8]  = {};
            uint8_t  sig_extra[2]  = { 0x1A, 0x0A }; // this never actually changes
            uint8_t  ownerPID      = OWNER_PID_NONE; // informational - may reflect what's on the version field in the var entries
            uint8_t  comment[42]   = {};
            uint16_t entries_len   = 0;
        };

        struct var_entry_t
        {
            uint16_t meta_length = 0; // byte count of the next 3 or 5 fields (== 11 or 13) depending on calcFlags, see below
            uint16_t data_length   = 0;
            uint8_t  typeID        = 0;
            uint8_t  varname[8]    = {};
            TIVarFileMinVersionByte version = VER_NONE; // present only if calcFlags >= TIFeatureFlags::hasFlash
            uint8_t  archivedFlag  = 0; // present only if calcFlags >= TIFeatureFlags::hasFlash
            uint16_t data_length2 = 0; // same as data_length
            data_t data;

            TIVarType _type{}; // has "full" type information (useful for appvars that have a "sub"type)
            void setArchived(bool archived) { archivedFlag = (archived ? 0x80 : 0); }
            void setVarName(const std::string& name);
            void determineFullType(void);
        };

        // comes right after the var header, so == its size
        static const constexpr uint16_t firstVarEntryOffset = sizeof(var_header_t::signature) + sizeof(var_header_t::sig_extra) + sizeof(var_header_t::ownerPID) + sizeof(var_header_t::comment) + sizeof(var_header_t::entries_len);
        static_assert(firstVarEntryOffset == 55, "firstVarEntryOffset size needs to be 55");

        static const constexpr uint16_t varEntryOldLength = sizeof(var_entry_t::data_length) + sizeof(var_entry_t::typeID) + sizeof(var_entry_t::varname);
        static_assert(varEntryOldLength == 0x0B, "varEntryOldLength size needs to be 11");

        static const constexpr uint16_t varEntryNewLength = varEntryOldLength + sizeof(var_entry_t::version) + sizeof(var_entry_t::archivedFlag);
        static_assert(varEntryNewLength == 0x0D, "varEntryNewLength size needs to be 13");

        TIVarFile() = delete;

        const var_header_t& getHeader() const { return header; }
        const std::vector<var_entry_t>& getVarEntries() const { return entries; }
        const TIModel& getCalcModel() const { return calcModel; }
        uint16_t getInstanceChecksum() const { return computedChecksum; }
        bool hasMultipleEntries() const { return entries.size() > 1; }

        static TIVarFile loadFromFile(const std::string& filePath);

        static TIVarFile createNew(const TIVarType& type, const std::string& name, const TIModel& model);
        static TIVarFile createNew(const TIVarType& type, const std::string& name);
        static TIVarFile createNew(const TIVarType& type);

        uint16_t getChecksumValueFromFile();

        void setContentFromData(const data_t& data, uint16_t entryIdx);
        void setContentFromData(const data_t& data);

        void setContentFromString(const std::string& str, const options_t& options, uint16_t entryIdx);
        void setContentFromString(const std::string& str, const options_t& options);
        void setContentFromString(const std::string& str);

        void setCalcModel(const TIModel& model);

        void setVarName(const std::string& name, uint16_t entryIdx);
        void setVarName(const std::string& name);
        void setArchived(bool flag, uint16_t entryIdx);
        void setArchived(bool flag);

        bool isCorrupt() const;

        data_t getRawContent(uint16_t entryIdx);
        data_t getRawContent();

        std::string getRawContentHexStr();

        std::string getReadableContent(const options_t& options, uint16_t entryIdx) const;
        std::string getReadableContent(const options_t& options) const;
        std::string getReadableContent() const;

        std::string saveVarToFile(std::string directory, std::string name);
        std::string saveVarToFile(std::string path);
        std::string saveVarToFile();

    private:
        TIVarFile(const TIVarType& type, const std::string& name, const TIModel& model);
        explicit TIVarFile(const std::string& filePath);

        void refreshMetadataFields();
        void checkVarEntriesVersionCompat() const;

        void makeHeaderFromFile();
        void makeVarEntriesFromFile();

        uint16_t computeChecksumFromInstanceData() const;
        uint16_t computeChecksumFromFileData() const;

        // Extends BinaryFile.
        uint16_t get_two_bytes_swapped() const
        {
            const uint8_t low = this->get_raw_byte();
            const uint8_t high = this->get_raw_byte();
            return low + (high << 8);
        }

        var_header_t header;
        std::vector<var_entry_t> entries;
        TIModel      calcModel;
        uint16_t     computedChecksum = 0;
        uint16_t     fileChecksum     = 0;
        bool         fromFile         = false;
        bool         corrupt          = false;

        data_t make_bin_data();

    };
}

#endif //TIVARS_LIB_CPP_TIVARFILE_H


// ===== src/TIModels.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIMODELS_H
#define TIMODELS_H

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'TIModel.h'
#include <unordered_map>

namespace tivars
{
    enum TIFeatureFlags
    {
        has82things  = 0b000000001, // (1 << 0);
        hasComplex   = 0b000000010, // (1 << 1);
        hasFlash     = 0b000000100, // (1 << 2);
        hasApps      = 0b000001000, // (1 << 3);
        hasClock     = 0b000010000, // (1 << 4);
        hasColorLCD  = 0b000100000, // (1 << 5);
        hasEZ80CPU   = 0b001000000, // (1 << 6);
        hasExactMath = 0b010000000, // (1 << 7);
        hasPython    = 0b100000000, // (1 << 8);
    };

    class TIModels
    {

    public:

        static TIModel fromName(const std::string& name);
        static TIModel fromSignature(const std::string& sig);
        static TIModel fromPID(uint8_t pid);

        static const std::unordered_map<std::string, TIModel>& all();

        static bool isValidPID(uint8_t pid);
        static bool isValidName(const std::string& name);
        static bool isValidSignature(const std::string& sig);

    };

}

#endif


// ===== src/TIVarTypes.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIVARTYPES_H
#define TIVARTYPES_H

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'TIVarType.h'
#include <unordered_map>

namespace tivars
{
    class TIVarTypes
    {

    public:
        static TIVarType fromName(const std::string& name);
        static TIVarType fromId(uint8_t id);

        static const std::unordered_map<std::string, TIVarType>& all();

        static bool isValidName(const std::string& name);
        static bool isValidID(uint8_t id);

    };
}

#endif //TIVARTYPES_H


// ===== src/tivarslib_utils.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIVARSLIB_UTILS_H
#define TIVARSLIB_UTILS_H

#include <vector>
#include <string>
#include <algorithm>
#include <array>

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'TIModel.h'
// amalgamated: removed local include 'TIVarType.h'

namespace tivars
{

template<typename T>
bool is_in_vector(const std::vector<T>& v, T element)
{
    return std::find(v.begin(), v.end(), element) != v.end();
}

template<typename T>
void vector_append(std::vector<T>& vec, const std::vector<T>& other)
{
    vec.insert(vec.end(), other.begin(), other.end());
}

unsigned char hexdec(const std::string& str);

data_t hex_string_to_bytes(const std::string& hex, const char* fieldName = "hex string");

std::string dechex(unsigned char i, bool zeropad = true);

std::string strtoupper(const std::string& str);

void replace_all(std::string& str, const std::string& from, const std::string& to);

std::vector<std::string> explode(const std::string& str, const std::string& delim);
std::vector<std::string> explode(const std::string& str, char delim);

std::string ltrim(std::string s, const char* t = " \t\n\r\f\v");

std::string rtrim(std::string s, const char* t = " \t\n\r\f\v");

std::string trim(const std::string& s, const char* t = " \t\n\r\f\v");

bool is_numeric(const std::string& str);

bool file_exists(const std::string& path);

std::string str_pad(const std::string& str, unsigned long pad_length, const std::string& pad_string = " ");

std::string multiple(int num, const std::string& var);
std::string multiple(long long num, const std::string& var);

std::string dec2frac(double num, const std::string& var = "", double err = 0.001);

std::string trimZeros(const std::string& str);

std::string entry_name_to_string(const TIVarType& type, const uint8_t* nameBytes, size_t size = 8);
std::string sanitize_for_host_filename(const std::string& name);
std::array<uint8_t, 3> rgb565_to_rgb888(uint16_t value);
std::string make_bmp_data_url(uint32_t width, uint32_t height, const data_t& rgbPixels);
std::string make_bmp_data_url_rgba(uint32_t width, uint32_t height, const data_t& rgbaPixels);

}

#endif


// ===== src/TIFlashFile.h =====

/*
 * Part of tivars_lib_cpp
 * (C) 2015-2026 Adrien "Adriweb" Bertrand
 * https://github.com/adriweb/tivars_lib_cpp
 * License: MIT
 */

#ifndef TIVARS_LIB_CPP_TIFLASHFILE_H
#define TIVARS_LIB_CPP_TIFLASHFILE_H

// amalgamated: removed local include 'CommonTypes.h'
// amalgamated: removed local include 'TIModel.h'
// amalgamated: removed local include 'TIVarType.h'

namespace tivars
{
    class TIFlashFile
    {
    public:
        struct flash_date_t
        {
            uint8_t day = 0;
            uint8_t month = 0;
            uint16_t year = 0;
        };

        struct flash_block_t
        {
            uint16_t address = 0;
            uint8_t blockType = 0x00;
            data_t data;
        };

        struct flash_header_t
        {
            std::string magic = magicStr;
            std::string revision = "0.0";
            uint8_t binaryFlag = intelDataFlag;
            uint8_t objectType = 0x00;
            flash_date_t date{};
            std::string name = "UNNAMED";
            std::vector<std::pair<uint8_t, uint8_t>> devices;
            uint8_t productId = 0;
            data_t calcData;
            bool hasChecksum = true;
            TIVarType type{};
            TIModel model{};
        };

        static constexpr char magicStr[] = "**TIFL**";
        static constexpr uint8_t rawBinaryDataFlag = 0x00;
        static constexpr uint8_t intelDataFlag = 0x01;
        static constexpr uint8_t defaultDeviceType = 0x73;
        static constexpr size_t magicByteCount = 8;
        static constexpr size_t revisionByteCount = 2;
        static constexpr size_t dateByteCount = 4;
        static constexpr size_t nameByteCount = 31;
        static constexpr size_t deviceFieldByteCount = 25;
        static constexpr size_t productIdByteCount = 1;
        static constexpr size_t dataSizeByteCount = 4;
        static constexpr size_t checksumByteCount = 2;
        static constexpr size_t headerByteCountWithoutChecksum = 78;

        TIFlashFile() = default;

        static TIFlashFile loadFromFile(const std::string& filePath);
        static TIFlashFile createNew(const TIVarType& type, const std::string& name, const TIModel& model, bool rawBinaryData = false);
        static TIFlashFile createNew(const TIVarType& type, const std::string& name, bool rawBinaryData = false);
        static TIFlashFile createNew(const TIVarType& type, bool rawBinaryData = false);

        const std::vector<flash_header_t>& getHeaders() const { return headers; }
        bool hasMultipleHeaders() const { return headers.size() > 1; }

        void addHeader(const TIVarType& type, const std::string& name, const TIModel& model, bool rawBinaryData = false);

        std::string getReadableContent(size_t headerIdx = 0) const;
        void setContentFromString(const std::string& str, size_t headerIdx = 0);

        data_t makeBinData() const;
        std::string saveToFile(const std::string& path) const;

    private:
        explicit TIFlashFile(const std::string& filePath);
        TIFlashFile(const TIVarType& type, const std::string& name, const TIModel& model, bool rawBinaryData);

        static flash_header_t parseHeader(const data_t& bytes, size_t offset, size_t* nextOffset);
        static size_t nextHeaderLength(const data_t& bytes, size_t offset);
        static data_t makeHeaderBytes(const flash_header_t& header);
        static uint16_t computeChecksum(const data_t& data);
        static std::vector<flash_block_t> parseIntelBlocks(const data_t& data);
        static data_t makeIntelData(const std::vector<flash_block_t>& blocks);
        static std::string blockToRecord(const flash_block_t& block);
        static flash_block_t recordToBlock(const std::string& record);
        static std::string extensionFor(const flash_header_t& header);
        static uint8_t defaultObjectTypeFor(const TIVarType& type);
        static data_t parseHex(const std::string& hex);
        static std::string toHex(const data_t& data);
        static uint8_t encodeBCDByte(uint8_t value);
        static uint8_t decodeBCDByte(uint8_t value);
        static flash_date_t parseBCDDate(const data_t& dateBytes);
        static data_t makeBCDDate(const flash_date_t& date);
        static std::string parseBCDRevision(const data_t& revisionBytes);
        static data_t makeBCDRevision(const std::string& revision);
        static TIModel modelFromProductId(uint8_t productId);

        std::vector<flash_header_t> headers;
        std::string filePath;
        bool fromFile = false;
    };
}

#endif

#endif // TIVARS_LIB_CPP_AMALGAMATED_HPP
