NAME = GDBTEST
DESCRIPTION = CEmu GDB regression fixture
COMPRESSED = NO
ARCHIVED = NO
HAS_PRINTF = NO
HAS_LIBC = NO
HAS_LIBCXX = NO
CFLAGS = -Wall -Wextra -Oz
include $(shell cedev-config --makefile)
