name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [master]

jobs:
  coverity:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Install Linux dependencies (Ubuntu 22.04+)
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends qt6-base-dev qmake6 qtchooser libgl1-mesa-dev libarchive-dev libudev-dev libusb-1.0-0-dev

    - name: set-up qt6
      run: |
        qtchooser -install qt6 $(which qmake6)
        sudo mv ~/.config/qtchooser/qt6.conf /usr/share/qtchooser/qt6.conf
        sudo mkdir -p /usr/lib/$(uname -p)-linux-gnu/qt-default/qtchooser
        sudo ln -n /usr/share/qtchooser/qt6.conf /usr/lib/$(uname -p)-linux-gnu/qt-default/qtchooser/default.conf
        echo "QT_SELECT=qt6" >> "$GITHUB_ENV"
        
    - name: Prepare build
      run: |
        set -e
        cd gui/qt/capture ; /bin/bash ./get_libpng-apng.sh ; cd ../../../
        mkdir build
        cd build
        qmake6 ../gui/qt
    
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        working-directory: "${{ github.workspace }}/build"

